/**
 * Share and export functionality for analysis results
 */

import type { StructuredAnalysisResult } from "./analyze-structured";
import { formatQALYs } from "./analyze-structured";

/**
 * Format analysis result as plain text for clipboard/sharing
 */
export function formatAnalysisForExport(result: StructuredAnalysisResult): string {
  const lines: string[] = [];

  // Header
  lines.push("=".repeat(60));
  lines.push(`QALY ANALYSIS: ${result.intervention}`);
  lines.push("=".repeat(60));
  lines.push("");

  // Counterfactual
  lines.push(`Compared to: ${result.counterfactual}`);
  lines.push("");

  // Main Impact
  lines.push("ESTIMATED QALY IMPACT");
  lines.push("-".repeat(60));
  lines.push(`Total: ${formatQALYs(result.summary.totalQALYs.median)}`);
  lines.push(
    `95% CI: ${formatQALYs(result.summary.totalQALYs.ci95Low)} to ${formatQALYs(result.summary.totalQALYs.ci95High)}`
  );
  lines.push(`Confidence: ${result.summary.confidenceLevel}`);
  lines.push(`Probability of benefit: ${(result.summary.probPositive * 100).toFixed(0)}%`);
  lines.push("");

  // Breakdown
  lines.push("BREAKDOWN");
  lines.push("-".repeat(60));
  lines.push(
    `Longevity: ${formatQALYs(result.simulation.breakdown.mortalityQALYs.median)} ` +
    `(95% CI: ${formatQALYs(result.simulation.breakdown.mortalityQALYs.ci95.low)} to ` +
    `${formatQALYs(result.simulation.breakdown.mortalityQALYs.ci95.high)})`
  );
  lines.push(
    `Quality: ${formatQALYs(result.simulation.breakdown.qualityQALYs.median)} ` +
    `(95% CI: ${formatQALYs(result.simulation.breakdown.qualityQALYs.ci95.low)} to ` +
    `${formatQALYs(result.simulation.breakdown.qualityQALYs.ci95.high)})`
  );
  lines.push("");

  // Confounding adjustment (if applied)
  if (result.simulation.confounding) {
    const conf = result.simulation.confounding;
    lines.push("CONFOUNDING ADJUSTMENT");
    lines.push("-".repeat(60));
    lines.push(
      `Estimated causal fraction: ${(conf.expectedCausalFraction * 100).toFixed(0)}% ` +
      `(95% CI: ${(conf.causalFractionCI.low * 100).toFixed(0)}–${(conf.causalFractionCI.high * 100).toFixed(0)}%)`
    );
    lines.push(
      `Estimate reduced by ${conf.comparison.reductionPercent.toFixed(0)}% ` +
      `to account for potential confounding.`
    );
    lines.push("");
  }

  // Mechanisms
  if (result.affectedMechanisms.length > 0) {
    lines.push("BIOLOGICAL MECHANISMS");
    lines.push("-".repeat(60));
    result.affectedMechanisms.forEach((m) => {
      lines.push(
        `• ${m.mechanism.replace(/_/g, " ")} (${m.direction}) - ${m.evidenceQuality} evidence`
      );
      if (m.affectedConditions.length > 0) {
        lines.push(`  Affects: ${m.affectedConditions.join(", ")}`);
      }
    });
    lines.push("");
  }

  // Evidence
  lines.push("EVIDENCE QUALITY");
  lines.push("-".repeat(60));
  lines.push(`Overall: ${result.evidence.quality}`);
  lines.push("");

  if (result.evidence.keyStudies.length > 0) {
    lines.push("Key Studies:");
    result.evidence.keyStudies.forEach((study) => {
      lines.push(`• ${study.citation} (${study.studyType})`);
    });
    lines.push("");
  }

  // Caveats
  if (result.evidence.caveats.length > 0) {
    lines.push("IMPORTANT CAVEATS");
    lines.push("-".repeat(60));
    result.evidence.caveats.forEach((caveat) => {
      lines.push(`• ${caveat}`);
    });
    lines.push("");
  }

  // Disclaimer
  lines.push("DISCLAIMER");
  lines.push("-".repeat(60));
  lines.push(
    "This analysis is based on peer-reviewed research but involves significant "
  );
  lines.push(
    "uncertainty and should not be considered medical advice. Individual results "
  );
  lines.push(
    "may vary based on baseline health, adherence, and other factors. Always "
  );
  lines.push(
    "consult healthcare professionals for medical decisions."
  );
  lines.push("");
  lines.push(`Generated by Optiqal AI • ${new Date().toLocaleDateString()}`);
  lines.push("=".repeat(60));

  return lines.join("\n");
}

/**
 * Format analysis result for PDF generation (structured data)
 */
export interface PDFData {
  title: string;
  subtitle: string;
  qalyImpact: string;
  confidenceInterval: string;
  confidenceLevel: string;
  sections: {
    title: string;
    items: string[];
  }[];
  disclaimer: string;
  generatedDate: string;
}

export function formatAnalysisForPDF(result: StructuredAnalysisResult): PDFData {
  const sections: PDFData["sections"] = [];

  // QALY Impact section
  sections.push({
    title: "QALY Impact",
    items: [
      `Total: ${formatQALYs(result.summary.totalQALYs.median)}`,
      `Probability of benefit: ${(result.summary.probPositive * 100).toFixed(0)}%`,
      `Confidence: ${result.summary.confidenceLevel}`,
    ],
  });

  // Breakdown section
  sections.push({
    title: "Breakdown",
    items: [
      `Longevity: ${formatQALYs(result.simulation.breakdown.mortalityQALYs.median)} ` +
      `(95% CI: ${formatQALYs(result.simulation.breakdown.mortalityQALYs.ci95.low)} to ` +
      `${formatQALYs(result.simulation.breakdown.mortalityQALYs.ci95.high)})`,
      `Quality: ${formatQALYs(result.simulation.breakdown.qualityQALYs.median)} ` +
      `(95% CI: ${formatQALYs(result.simulation.breakdown.qualityQALYs.ci95.low)} to ` +
      `${formatQALYs(result.simulation.breakdown.qualityQALYs.ci95.high)})`,
    ],
  });

  // Evidence section
  const evidenceItems: string[] = [
    `Overall quality: ${result.evidence.quality}`,
  ];

  if (result.affectedMechanisms.length > 0) {
    evidenceItems.push("");
    evidenceItems.push("Biological mechanisms:");
    result.affectedMechanisms.forEach((m) => {
      evidenceItems.push(
        `• ${m.mechanism.replace(/_/g, " ")} (${m.direction}) - ${m.evidenceQuality}`
      );
    });
  }

  if (result.evidence.keyStudies.length > 0) {
    evidenceItems.push("");
    evidenceItems.push("Key studies:");
    result.evidence.keyStudies.forEach((study) => {
      evidenceItems.push(`• ${study.citation} (${study.studyType})`);
    });
  }

  sections.push({
    title: "Evidence",
    items: evidenceItems,
  });

  // Important notes section
  const notesItems: string[] = [];

  if (result.simulation.confounding) {
    const conf = result.simulation.confounding;
    notesItems.push(
      `Confounding adjustment applied: ~${(conf.expectedCausalFraction * 100).toFixed(0)}% estimated to be causal`
    );
  }

  if (result.evidence.caveats.length > 0) {
    notesItems.push("");
    notesItems.push("Caveats:");
    result.evidence.caveats.forEach((caveat) => {
      notesItems.push(`• ${caveat}`);
    });
  }

  sections.push({
    title: "Important Notes",
    items: notesItems,
  });

  return {
    title: result.intervention,
    subtitle: `Compared to: ${result.counterfactual}`,
    qalyImpact: formatQALYs(result.summary.totalQALYs.median),
    confidenceInterval: `${formatQALYs(result.summary.totalQALYs.ci95Low)} to ${formatQALYs(result.summary.totalQALYs.ci95High)}`,
    confidenceLevel: result.summary.confidenceLevel,
    sections,
    disclaimer:
      "This analysis is based on peer-reviewed research but involves significant uncertainty and should not be considered medical advice. Always consult healthcare professionals for medical decisions.",
    generatedDate: new Date().toLocaleDateString(),
  };
}
