"""Content-addressed computation graphs for Optiqal."""

from .decl import (
    DESCRIPTIVE_FIELDS,
    GATE_OUTCOMES,
    ROLES,
    TIERS,
    CompiledGraph,
    Graph,
    Node,
    Param,
    SourceRef,
    compile_graph,
)
from .errors import (
    GraphError,
    GraphRuntimeError,
    KernelRegistrationError,
    ManifestError,
    NodeExecutionError,
    NodeRejectedError,
    StoreCorruptError,
    StoreMissError,
    StoreUnavailableError,
)
from .kernel import (
    Capabilities,
    Determinism,
    Kernel,
    KernelBase,
    KernelContext,
    KernelRegistry,
    KernelResult,
    Numeric,
    NumericScope,
    Tolerance,
    source_hash,
)

__all__ = [
    "DESCRIPTIVE_FIELDS",
    "GATE_OUTCOMES",
    "ROLES",
    "TIERS",
    "Capabilities",
    "CompiledGraph",
    "Determinism",
    "Graph",
    "GraphError",
    "GraphRuntimeError",
    "Kernel",
    "KernelBase",
    "KernelContext",
    "KernelRegistrationError",
    "KernelRegistry",
    "KernelResult",
    "ManifestError",
    "Node",
    "NodeRejectedError",
    "NodeExecutionError",
    "Numeric",
    "NumericScope",
    "Param",
    "SourceRef",
    "StoreCorruptError",
    "StoreMissError",
    "StoreUnavailableError",
    "Tolerance",
    "compile_graph",
    "source_hash",
]
