"""Content-addressed computation graphs for Optiqal."""

from .canonical import canonical_json, normative, sha256_domain
from .decl import (
    DESCRIPTIVE_FIELDS,
    GATE_OUTCOMES,
    ROLES,
    TIERS,
    CompiledGraph,
    Graph,
    Node,
    Param,
    SourceRef,
    compile_graph,
)
from .errors import (
    GraphError,
    GraphRuntimeError,
    KernelRegistrationError,
    ManifestError,
    NodeExecutionError,
    NodeRejectedError,
    StoreCorruptError,
    StoreMissError,
    StoreUnavailableError,
)
from .kernel import (
    Capabilities,
    Determinism,
    Kernel,
    KernelBase,
    KernelContext,
    KernelRegistry,
    KernelResult,
    Numeric,
    NumericScope,
    Tolerance,
    source_hash,
)
from .keys import artifact_key, node_key, platform_fingerprint, seed, source_key
from .store import ContentStore, ResumePolicy, StoredResult

__all__ = [
    "DESCRIPTIVE_FIELDS",
    "GATE_OUTCOMES",
    "ROLES",
    "TIERS",
    "Capabilities",
    "CompiledGraph",
    "ContentStore",
    "Determinism",
    "Graph",
    "GraphError",
    "GraphRuntimeError",
    "Kernel",
    "KernelBase",
    "KernelContext",
    "KernelRegistrationError",
    "KernelRegistry",
    "KernelResult",
    "ManifestError",
    "Node",
    "NodeRejectedError",
    "NodeExecutionError",
    "Numeric",
    "NumericScope",
    "Param",
    "ResumePolicy",
    "SourceRef",
    "StoreCorruptError",
    "StoreMissError",
    "StoreUnavailableError",
    "StoredResult",
    "Tolerance",
    "artifact_key",
    "canonical_json",
    "compile_graph",
    "node_key",
    "normative",
    "platform_fingerprint",
    "seed",
    "sha256_domain",
    "source_hash",
    "source_key",
]
