"use client";

import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Copy, Download, Share2, Check } from "lucide-react";
import type { StructuredAnalysisResult } from "@/lib/analyze-structured";
import { formatAnalysisForExport, formatAnalysisForPDF } from "@/lib/share";
import { jsPDF } from "jspdf";

interface ShareButtonsProps {
  result: StructuredAnalysisResult;
}

export function ShareButtons({ result }: ShareButtonsProps) {
  const [copied, setCopied] = useState(false);
  const [isGeneratingPDF, setIsGeneratingPDF] = useState(false);

  const handleCopyToClipboard = async () => {
    try {
      const text = formatAnalysisForExport(result);
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error("Failed to copy to clipboard:", error);
      alert("Failed to copy to clipboard. Please try again.");
    }
  };

  const handleDownloadPDF = async () => {
    setIsGeneratingPDF(true);
    try {
      const data = formatAnalysisForPDF(result);

      // Create PDF with jsPDF
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const maxWidth = pageWidth - 2 * margin;
      let yPosition = margin;

      // Helper to add text with word wrapping
      const addText = (
        text: string,
        fontSize: number,
        isBold = false,
        color: [number, number, number] = [0, 0, 0]
      ) => {
        doc.setFontSize(fontSize);
        doc.setFont("helvetica", isBold ? "bold" : "normal");
        doc.setTextColor(color[0], color[1], color[2]);

        const lines = doc.splitTextToSize(text, maxWidth);

        // Check if we need a new page
        if (yPosition + lines.length * fontSize * 0.35 > pageHeight - margin) {
          doc.addPage();
          yPosition = margin;
        }

        doc.text(lines, margin, yPosition);
        yPosition += lines.length * fontSize * 0.35 + 3;
      };

      // Header
      doc.setFillColor(49, 151, 149); // Primary color
      doc.rect(0, 0, pageWidth, 40, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text("QALY Analysis Report", margin, 25);

      yPosition = 50;

      // Title
      addText(data.title, 16, true, [49, 151, 149]);
      addText(data.subtitle, 10, false, [100, 100, 100]);
      yPosition += 5;

      // Main Impact
      doc.setFillColor(240, 240, 240);
      doc.rect(margin - 5, yPosition - 5, maxWidth + 10, 35, "F");
      yPosition += 5;
      addText("Estimated QALY Impact", 12, true);
      addText(data.qalyImpact, 16, true, [49, 151, 149]);
      addText(`95% CI: ${data.confidenceInterval}`, 9, false, [100, 100, 100]);
      addText(`Confidence: ${data.confidenceLevel}`, 9, false, [100, 100, 100]);
      yPosition += 10;

      // Sections
      for (const section of data.sections) {
        // Section title
        addText(section.title.toUpperCase(), 11, true, [49, 151, 149]);

        // Section items
        for (const item of section.items) {
          if (item === "") {
            yPosition += 2;
          } else {
            addText(item, 9, false);
          }
        }

        yPosition += 5;
      }

      // Disclaimer
      yPosition += 5;
      doc.setFillColor(255, 243, 224);
      const disclaimerHeight = doc.splitTextToSize(data.disclaimer, maxWidth).length * 9 * 0.35 + 15;

      if (yPosition + disclaimerHeight > pageHeight - margin) {
        doc.addPage();
        yPosition = margin;
      }

      doc.rect(margin - 5, yPosition - 5, maxWidth + 10, disclaimerHeight, "F");
      yPosition += 5;
      addText("DISCLAIMER", 10, true, [180, 83, 9]);
      addText(data.disclaimer, 8, false, [60, 60, 60]);

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Generated by Optiqal AI • ${data.generatedDate}`,
        pageWidth / 2,
        pageHeight - 10,
        { align: "center" }
      );

      // Download
      const filename = `optiqal-analysis-${result.intervention.toLowerCase().replace(/\s+/g, "-")}.pdf`;
      doc.save(filename);
    } catch (error) {
      console.error("Failed to generate PDF:", error);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setIsGeneratingPDF(false);
    }
  };

  const handleShare = async () => {
    // Future: implement share link functionality
    // For now, just copy to clipboard
    await handleCopyToClipboard();
  };

  return (
    <div className="flex flex-wrap gap-2">
      <Button
        variant="outline"
        size="sm"
        onClick={handleCopyToClipboard}
        disabled={copied}
      >
        {copied ? (
          <>
            <Check className="w-4 h-4 mr-2" />
            Copied!
          </>
        ) : (
          <>
            <Copy className="w-4 h-4 mr-2" />
            Copy
          </>
        )}
      </Button>

      <Button
        variant="outline"
        size="sm"
        onClick={handleDownloadPDF}
        disabled={isGeneratingPDF}
      >
        <Download className="w-4 h-4 mr-2" />
        {isGeneratingPDF ? "Generating..." : "Download PDF"}
      </Button>

      <Button
        variant="outline"
        size="sm"
        onClick={handleShare}
        disabled
        title="Share link (coming soon)"
      >
        <Share2 className="w-4 h-4 mr-2" />
        Share
      </Button>
    </div>
  );
}
