import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, render, screen } from "@testing-library/react";
import { StrictMode } from "react";
import { BaselineWorkbench } from "@/components/predict/baseline-workbench";
import type { BaselineResponse } from "@/lib/baseline-types";
import { DEFAULT_PROFILE } from "@/types";
import modelResponses from "@/lib/__fixtures__/model-responses.json";

function makeResponse(
  pointEstimate: Partial<BaselineResponse["point_estimate"]> = {},
  qalyDiscountRate = 0.03
): BaselineResponse {
  return {
    meta: {
      model: "baseline_v1",
      qaly_discount_rate: qalyDiscountRate,
      explicit_inputs_only: true,
      profile: {
        age: 39,
        sex: "male",
        bmi_category: "normal",
        smoking_status: "never",
        has_diabetes: false,
        has_hypertension: false,
        activity_level: "active",
      },
    },
    point_estimate: {
      remaining_life_expectancy: 41.2,
      expected_death_age: 80.2,
      remaining_qalys: 35.1,
      current_quality_weight: 0.96,
      ...pointEstimate,
    },
    risk: {
      lifestyle_multiplier: 0.92,
      condition_multiplier: 1,
      sleep_multiplier: 1.03,
      raw_multiplier: 0.95,
      calibration_factor: 1.01,
      calibrated_multiplier: 0.96,
    },
    survival_curve: [
      { age: 39, survival_probability: 1, quality_weight: 0.96, expected_qaly: 0.96 },
    ],
    sleep_estimate: null,
  };
}

function mockFetchOnce(response: BaselineResponse) {
  const fetchMock = vi.fn().mockResolvedValue({
    ok: true,
    json: async () => response,
  });
  vi.stubGlobal("fetch", fetchMock);
  return fetchMock;
}

describe("BaselineWorkbench", () => {
  beforeEach(() => {
    localStorage.clear();
  });

  afterEach(() => {
    cleanup();
    vi.unstubAllGlobals();
    vi.restoreAllMocks();
  });

  it("shows the medical disclaimer", async () => {
    mockFetchOnce(makeResponse());
    render(<BaselineWorkbench />);
    // Auto-runs after hydration; wait for results.
    await screen.findByText(/remaining life expectancy/i);
    expect(
      screen.getAllByText(/statistical estimates, not medical advice/i).length
    ).toBeGreaterThan(0);
    expect(
      screen.getAllByText(/consult a healthcare professional before acting/i).length
    ).toBeGreaterThan(0);
  });

  it("renders confidence intervals next to life expectancy and QALYs", async () => {
    mockFetchOnce(
      makeResponse({
        remaining_life_expectancy: 41.2,
        remaining_life_expectancy_ci: [36.4, 45.9],
        remaining_qalys: 35.1,
        remaining_qalys_ci: [30.2, 39.7],
      })
    );
    render(<BaselineWorkbench />);
    await screen.findByText(/remaining life expectancy/i);

    // Range bounds rounded to whole years to reduce false precision.
    expect(screen.getByText(/range 36\s*[–-]\s*46/i)).toBeInTheDocument();
    expect(screen.getByText(/range 30\s*[–-]\s*40/i)).toBeInTheDocument();
    expect(screen.getByText(/3% QALY discount/i)).toBeInTheDocument();
  });

  it("renders the QALY discount rate returned by the engine", async () => {
    mockFetchOnce(makeResponse({}, 0.015));
    render(<BaselineWorkbench />);
    await screen.findByText(/remaining life expectancy/i);

    expect(screen.getByText("1.5% QALY discount")).toBeInTheDocument();
    expect(screen.queryByText("0% discount")).toBeNull();
  });

  it("labels the other-sex option as the average the baseline model computes", async () => {
    mockFetchOnce(makeResponse());
    render(<BaselineWorkbench />);
    await screen.findByText(/remaining life expectancy/i);

    const option = screen.getByRole("option", { name: "Other / average" });
    expect(option).toHaveValue("other");
    // Regression: the label once promised the male life table, which only the
    // frontier fallback uses.
    expect(screen.queryByText(/male life table/i)).toBeNull();

    // The real Python baseline (fixtures generated by
    // src/lib/__fixtures__/generate_model_responses.py) averages the male and
    // female projections for "other", so its estimate differs from the male
    // one and lies between the two.
    const lifeExpectancy = (name: string) =>
      modelResponses.baseline.find((sample) => sample.name === name)!.response
        .point_estimate.remaining_life_expectancy;
    const male = lifeExpectancy("male_default");
    const female = lifeExpectancy("female_default");
    const other = lifeExpectancy("other_default");
    expect(other).not.toBe(male);
    expect(other).toBeGreaterThanOrEqual(Math.min(male, female));
    expect(other).toBeLessThanOrEqual(Math.max(male, female));
  });

  it("omits ranges when the response has no confidence intervals", async () => {
    mockFetchOnce(makeResponse());
    render(<BaselineWorkbench />);
    await screen.findByText(/remaining life expectancy/i);
    expect(screen.queryByText(/^range \d/i)).toBeNull();
  });

  it("preserves a saved profile during StrictMode hydration", async () => {
    localStorage.setItem(
      "optiqal-baseline-profile-v1",
      JSON.stringify({ ...DEFAULT_PROFILE, age: 64 })
    );
    localStorage.setItem(
      "optiqal-baseline-sleep-v1",
      JSON.stringify({ recovery_score: 82 })
    );
    mockFetchOnce(makeResponse());

    render(
      <StrictMode>
        <BaselineWorkbench />
      </StrictMode>
    );
    await screen.findByText(/remaining life expectancy/i);

    expect(screen.getByLabelText("Age")).toHaveValue(64);
    expect(JSON.parse(localStorage.getItem("optiqal-baseline-profile-v1")!)).toMatchObject({
      age: 64,
    });
    expect(localStorage.getItem("optiqal-baseline-sleep-v1")).toBe(
      JSON.stringify({ recovery_score: 82 })
    );
  });
});
