#!/usr/bin/env python3
"""
Download Pan-UKB GWAS Summary Statistics

This script provides instructions and automation for downloading Pan-UKB summary
statistics used in OptiqAL's MR validation analysis.

Data Source: Pan-UK Biobank (Pan-UKB)
URL: https://pan.ukbb.broadinstitute.org/
Citation: Pan-UKB Team (2022). Pan-ancestry genetic analysis of the UK Biobank.
          https://pan.ukbb.broadinstitute.org/

IMPORTANT: Pan-UKB data is publicly available but users should review and comply
with UK Biobank data access policies: https://www.ukbiobank.ac.uk/
"""

import sys
from pathlib import Path
from typing import Dict

# Phenotypes used in OptiqAL MR validation
PHENOTYPES: Dict[str, Dict[str, str]] = {
    "bmi": {
        "id": "21001_irnt",
        "description": "Body Mass Index (BMI)",
        "url": "https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/continuous-21001_irnt-both_sexes-EUR.tsv.bgz",
        "filename": "bmi.tsv.bgz",
        "use": "Exposure variable for MR analysis"
    },
    "t2dm": {
        "id": "E11",
        "description": "Type 2 Diabetes Mellitus",
        "url": "https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/E11-both_sexes-EUR.tsv.bgz",
        "filename": "t2dm.tsv.bgz",
        "use": "Outcome: validate BMI → T2DM hazard ratio"
    },
    "mi": {
        "id": "I21",
        "description": "Myocardial Infarction (MI/Heart Attack)",
        "url": "https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/I21-both_sexes-EUR.tsv.bgz",
        "filename": "mi.tsv.bgz",
        "use": "Outcome: validate BMI → CVD hazard ratio"
    },
    "melanoma": {
        "id": "C43",
        "description": "Melanoma (negative control)",
        "url": "https://pan-ukb-us-east-1.s3.amazonaws.com/sumstats_flat_files/C43-both_sexes-EUR.tsv.bgz",
        "filename": "melanoma.tsv.bgz",
        "use": "Negative control: BMI should not cause melanoma"
    }
}

OUTPUT_DIR = Path(__file__).parent.parent / "data" / "pan-ukb" / "sumstats"


def print_instructions():
    """Print manual download instructions"""
    print("=" * 80)
    print("PAN-UKB GWAS SUMMARY STATISTICS DOWNLOAD INSTRUCTIONS")
    print("=" * 80)
    print()
    print("Data will be downloaded to:")
    print(f"  {OUTPUT_DIR.absolute()}")
    print()
    print("Required phenotypes for OptiqAL MR validation:")
    print()

    for key, info in PHENOTYPES.items():
        print(f"  [{key.upper()}] {info['description']}")
        print(f"    Phenotype ID: {info['id']}")
        print(f"    Use: {info['use']}")
        print(f"    File: {info['filename']}")
        print(f"    URL: {info['url']}")
        print()

    print("=" * 80)
    print("DOWNLOAD METHODS")
    print("=" * 80)
    print()
    print("Option 1: Manual download with wget/curl")
    print("-" * 40)
    for key, info in PHENOTYPES.items():
        print(f"# Download {info['description']}")
        print(f"wget -O {OUTPUT_DIR / info['filename']} \\")
        print(f"  '{info['url']}'")
        print()

    print("Option 2: Use this script with urllib (no dependencies)")
    print("-" * 40)
    print("  python scripts/download-pan-ukb.py --download")
    print()

    print("Option 3: Use wget in batch mode")
    print("-" * 40)
    print("  python scripts/download-pan-ukb.py --generate-wget-script > download.sh")
    print("  chmod +x download.sh")
    print("  ./download.sh")
    print()

    print("=" * 80)
    print("DATA FORMAT")
    print("=" * 80)
    print()
    print("Files are bgzip-compressed TSV with columns:")
    print("  - chr: chromosome")
    print("  - pos: position (GRCh37)")
    print("  - ref: reference allele")
    print("  - alt: alternate allele")
    print("  - beta_EUR: effect size (European ancestry)")
    print("  - se_EUR: standard error")
    print("  - neglog10_pval_EUR: -log10(p-value)")
    print("  - AF_EUR: allele frequency")
    print("  - n_cases_EUR / n_controls_EUR (binary traits)")
    print()
    print("File sizes:")
    for key, info in PHENOTYPES.items():
        size = "~2.3 GB" if key == "bmi" else "~1.6 GB" if key == "mi" else "~2.5 GB" if key == "t2dm" else "~500 MB"
        print(f"  {info['filename']}: {size}")
    print()


def generate_wget_script():
    """Generate a bash script for wget download"""
    print("#!/bin/bash")
    print("# Auto-generated wget script for Pan-UKB downloads")
    print(f"# Generated by: {Path(__file__).name}")
    print()
    print(f'OUTPUT_DIR="{OUTPUT_DIR.absolute()}"')
    print('mkdir -p "$OUTPUT_DIR"')
    print()

    for key, info in PHENOTYPES.items():
        print(f"# {info['description']}")
        print(f'echo "Downloading {info["description"]}..."')
        print(f'wget -O "$OUTPUT_DIR/{info["filename"]}" \\')
        print(f'  "{info["url"]}"')
        print()


def download_with_urllib():
    """Download using Python's urllib (no external dependencies)"""
    import urllib.request
    import shutil

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    for key, info in PHENOTYPES.items():
        output_path = OUTPUT_DIR / info["filename"]

        if output_path.exists():
            print(f"✓ {info['filename']} already exists, skipping")
            continue

        print(f"Downloading {info['description']}...")
        print(f"  URL: {info['url']}")
        print(f"  Output: {output_path}")

        try:
            with urllib.request.urlopen(info["url"]) as response:
                total_size = int(response.headers.get('content-length', 0))
                print(f"  Size: {total_size / 1e9:.2f} GB")

                with open(output_path, 'wb') as out_file:
                    shutil.copyfileobj(response, out_file)

            print(f"✓ Downloaded {info['filename']}")
        except Exception as e:
            print(f"✗ Error downloading {info['filename']}: {e}")
            if output_path.exists():
                output_path.unlink()

    print()
    print("Download complete!")
    print(f"Files saved to: {OUTPUT_DIR.absolute()}")


def main():
    """Main entry point"""
    if len(sys.argv) > 1:
        if sys.argv[1] == "--download":
            download_with_urllib()
        elif sys.argv[1] == "--generate-wget-script":
            generate_wget_script()
        elif sys.argv[1] == "--help":
            print_instructions()
        else:
            print(f"Unknown option: {sys.argv[1]}")
            print("Usage: python download-pan-ukb.py [--download|--generate-wget-script|--help]")
            sys.exit(1)
    else:
        print_instructions()


if __name__ == "__main__":
    main()
