"""Unit tests for the optiqal.genetics module.

Uses synthetic 23andMe-format raw data so tests run without requiring
Max's real file. Covers parser, PGx caller, phenotype assignment,
actionable findings, GeneticProfile construction, and the
GeneticEffectRule → catalog multiplier wiring.
"""

from pathlib import Path

import pytest

from optiqal.genetics import (
    GeneticEffectRule,
    GeneticProfile,
    build_genetic_profile,
    call_apoe,
    call_ashkenazi_brca,
    call_cyp2c19,
    call_cyp2d6,
    call_hfe,
    diplotype_to_phenotype,
    parse_23andme,
)
from optiqal.genetics.parser import parse_ancestry, detect_and_parse


def _write_23andme(tmp_path: Path, genotypes: dict[str, tuple[str, int, str]]) -> Path:
    """Write a synthetic 23andMe raw file. genotypes = {rsid: (chrom, pos, gt)}."""
    path = tmp_path / "genome.txt"
    lines = [
        "# This data file generated by 23andMe at: synthetic-test-fixture",
        "# rsid\tchromosome\tposition\tgenotype",
    ]
    for rsid, (chrom, pos, gt) in genotypes.items():
        lines.append(f"{rsid}\t{chrom}\t{pos}\t{gt}")
    path.write_text("\n".join(lines) + "\n")
    return path


class TestParser:
    def test_parse_23andme_basic(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs4477212": ("1", 82154, "AA"),
            "rs3094315": ("1", 752566, "AG"),
            "i5000001": ("1", 900000, "CC"),
        })
        calls = parse_23andme(p)
        assert len(calls) == 3
        assert calls["rs4477212"].genotype == "AA"
        assert calls["rs3094315"].chromosome == "1"
        assert calls["rs3094315"].position == 752566

    def test_parser_handles_no_calls(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs1": ("1", 100, "--"),
            "rs2": ("1", 200, "AA"),
        })
        calls = parse_23andme(p)
        assert calls["rs1"].is_no_call
        assert not calls["rs2"].is_no_call

    def test_parser_ignores_malformed_lines(self, tmp_path):
        path = tmp_path / "genome.txt"
        path.write_text(
            "# header\n"
            "# rsid\tchromosome\tposition\tgenotype\n"
            "rs1\t1\tNOT_A_NUMBER\tAA\n"
            "rs2\t1\t200\tAA\n"
        )
        calls = parse_23andme(path)
        assert "rs2" in calls
        assert "rs1" not in calls

    def test_ancestry_format(self, tmp_path):
        p = tmp_path / "ancestry.txt"
        p.write_text(
            "#AncestryDNA raw data download\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "rs4477212\t1\t82154\tA\tA\n"
            "rs3094315\t1\t752566\tA\tG\n"
        )
        calls = parse_ancestry(p)
        assert calls["rs4477212"].genotype == "AA"
        assert calls["rs3094315"].genotype == "AG"

    def test_detect_ancestry(self, tmp_path):
        p = tmp_path / "ancestry.txt"
        p.write_text(
            "#AncestryDNA raw data download\n"
            "rsid\tchromosome\tposition\tallele1\tallele2\n"
            "rs4477212\t1\t82154\tA\tA\n"
        )
        calls = detect_and_parse(p)
        assert calls["rs4477212"].genotype == "AA"


class TestCyp2d6:
    def test_reference_diplotype(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs3892097": ("22", 42128945, "GG"),  # *4 absent
            "rs1065852": ("22", 42130692, "CC"),  # *10 absent
            "rs28371706": ("22", 42127941, "CC"),  # *17 absent
            "rs28371725": ("22", 42129770, "GG"),  # *41 absent
        })
        calls = parse_23andme(p)
        dp = call_cyp2d6(calls)
        assert dp.diplotype == "*1/*1"
        assert dp.activity_score == 2.0
        assert diplotype_to_phenotype(dp) == "normal_metabolizer"

    def test_heterozygous_star4(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs3892097": ("22", 42128945, "GA"),  # *4/*1
            "rs1065852": ("22", 42130692, "CC"),
            "rs28371706": ("22", 42127941, "CC"),
            "rs28371725": ("22", 42129770, "GG"),
        })
        dp = call_cyp2d6(parse_23andme(p))
        assert "*4" in (dp.allele1, dp.allele2)
        # Activity score = 1.0 (*4 = 0, *1 = 1.0)
        assert dp.activity_score == 1.0
        assert diplotype_to_phenotype(dp) == "intermediate_metabolizer"

    def test_homozygous_star4_poor_metabolizer(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs3892097": ("22", 42128945, "AA"),  # *4/*4
            "rs1065852": ("22", 42130692, "CC"),
            "rs28371706": ("22", 42127941, "CC"),
            "rs28371725": ("22", 42129770, "GG"),
        })
        dp = call_cyp2d6(parse_23andme(p))
        assert dp.allele1 == "*4" and dp.allele2 == "*4"
        assert dp.activity_score == 0.0
        assert diplotype_to_phenotype(dp) == "poor_metabolizer"


class TestCyp2c19:
    def test_reference_normal(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs4244285": ("10", 96541616, "GG"),
            "rs4986893": ("10", 96540410, "GG"),
            "rs12248560": ("10", 96522463, "CC"),
        })
        dp = call_cyp2c19(parse_23andme(p))
        assert dp.diplotype == "*1/*1"
        assert diplotype_to_phenotype(dp) == "normal_metabolizer"

    def test_star2_hetero_is_im(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs4244285": ("10", 96541616, "GA"),  # *2/*1
            "rs4986893": ("10", 96540410, "GG"),
            "rs12248560": ("10", 96522463, "CC"),
        })
        dp = call_cyp2c19(parse_23andme(p))
        assert "*2" in (dp.allele1, dp.allele2)
        assert diplotype_to_phenotype(dp) == "intermediate_metabolizer"

    def test_star17_homo_is_um(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs4244285": ("10", 96541616, "GG"),
            "rs4986893": ("10", 96540410, "GG"),
            "rs12248560": ("10", 96522463, "TT"),  # *17/*17
        })
        dp = call_cyp2c19(parse_23andme(p))
        assert dp.allele1 == "*17" and dp.allele2 == "*17"
        assert diplotype_to_phenotype(dp) == "ultrarapid_metabolizer"

    def test_star2_homo_is_pm(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs4244285": ("10", 96541616, "AA"),  # *2/*2
            "rs4986893": ("10", 96540410, "GG"),
            "rs12248560": ("10", 96522463, "CC"),
        })
        dp = call_cyp2c19(parse_23andme(p))
        assert dp.allele1 == "*2" and dp.allele2 == "*2"
        assert diplotype_to_phenotype(dp) == "poor_metabolizer"


class TestActionable:
    def test_hfe_c282y_homozygous_flagged(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs1800562": ("6", 26093141, "AA"),  # C282Y/C282Y
            "rs1799945": ("6", 26091179, "CC"),
        })
        findings = call_hfe(parse_23andme(p))
        assert len(findings) == 1
        assert "High-penetrance" in findings[0].clinical_significance

    def test_hfe_wild_type(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs1800562": ("6", 26093141, "GG"),
            "rs1799945": ("6", 26091179, "CC"),
        })
        findings = call_hfe(parse_23andme(p))
        assert len(findings) == 1
        assert "No pathogenic" in findings[0].clinical_significance

    def test_apoe_e3_e4(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs429358": ("19", 45411941, "CT"),
            "rs7412": ("19", 45412079, "CC"),
        })
        findings = call_apoe(parse_23andme(p))
        assert len(findings) == 1
        assert findings[0].zygosity == "e3/e4"

    def test_apoe_e3_e3_reference(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs429358": ("19", 45411941, "TT"),
            "rs7412": ("19", 45412079, "CC"),
        })
        findings = call_apoe(parse_23andme(p))
        assert findings[0].zygosity == "e3/e3"

    def test_brca_ashkenazi_negative_panel(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs80357914": ("17", 41276046, "AG"),  # BRCA1 185delAG ref
            "rs80357906": ("17", 41244936, "--"),
            "rs80359550": ("13", 32914438, "TT"),  # BRCA2 6174delT ref
        })
        findings = call_ashkenazi_brca(parse_23andme(p))
        assert len(findings) == 1
        assert findings[0].zygosity == "absent"

    def test_brca_ashkenazi_detects_23andme_deletion_indel(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs80357914": ("17", 41276046, "DI"),  # BRCA1 185delAG carrier
            "rs80357906": ("17", 41244936, "--"),
            "rs80359550": ("13", 32914438, "TT"),
        })

        findings = call_ashkenazi_brca(parse_23andme(p))

        assert [(finding.locus, finding.zygosity) for finding in findings] == [
            ("BRCA1 185delAG", "heterozygous")
        ]

    def test_brca_ashkenazi_detects_23andme_insertion_indel(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs80357914": ("17", 41276046, "AG"),
            "rs80357906": ("17", 41244936, "DI"),  # BRCA1 5382insC carrier
            "rs80359550": ("13", 32914438, "TT"),
        })

        findings = call_ashkenazi_brca(parse_23andme(p))

        assert [(finding.locus, finding.zygosity) for finding in findings] == [
            ("BRCA1 5382insC", "heterozygous")
        ]


class TestGeneticProfile:
    def test_build_from_file(self, tmp_path):
        p = _write_23andme(tmp_path, {
            # CYP2D6 reference
            "rs3892097": ("22", 42128945, "GG"),
            "rs1065852": ("22", 42130692, "CC"),
            "rs28371706": ("22", 42127941, "CC"),
            "rs28371725": ("22", 42129770, "GG"),
            # CYP2C19 reference
            "rs4244285": ("10", 96541616, "GG"),
            "rs4986893": ("10", 96540410, "GG"),
            "rs12248560": ("10", 96522463, "CC"),
            # HFE wild-type
            "rs1800562": ("6", 26093141, "GG"),
            "rs1799945": ("6", 26091179, "CC"),
            # APOE e3/e3
            "rs429358": ("19", 45411941, "TT"),
            "rs7412": ("19", 45412079, "CC"),
        })
        gp = build_genetic_profile(p, run_ashkenazi_brca=False)
        assert gp.phenotypes["CYP2D6"] == "normal_metabolizer"
        assert gp.phenotypes["CYP2C19"] == "normal_metabolizer"
        assert gp.has_phenotype("CYP2D6", "normal_metabolizer")
        # No actionable findings from reference APOE
        assert not gp.has_actionable("BRCA")

    def test_raw_genotypes_not_retained(self, tmp_path):
        p = _write_23andme(tmp_path, {
            "rs3892097": ("22", 42128945, "AA"),  # CYP2D6 *4/*4
            "rs1065852": ("22", 42130692, "CC"),
            "rs28371706": ("22", 42127941, "CC"),
            "rs28371725": ("22", 42129770, "GG"),
            "rs4244285": ("10", 96541616, "GG"),
            "rs4986893": ("10", 96540410, "GG"),
            "rs12248560": ("10", 96522463, "CC"),
            "rs429358": ("19", 45411941, "TT"),
            "rs7412": ("19", 45412079, "CC"),
        })
        gp = build_genetic_profile(p, run_ashkenazi_brca=False)
        # Privacy check: GeneticProfile fields should contain no raw
        # {rsid: genotype} mapping.
        import dataclasses
        field_names = {f.name for f in dataclasses.fields(gp)}
        assert "raw_genotypes" not in field_names
        assert "calls" not in field_names


class TestGeneticEffectRule:
    def test_rule_matches_only_on_phenotype(self):
        gp_um = GeneticProfile(phenotypes={"CYP2D6": "ultrarapid_metabolizer"})
        gp_nm = GeneticProfile(phenotypes={"CYP2D6": "normal_metabolizer"})
        rule = GeneticEffectRule(
            gene="CYP2D6",
            phenotype="ultrarapid_metabolizer",
            multiplier=0.3,
        )
        assert rule.matches(gp_um)
        assert not rule.matches(gp_nm)
        assert not rule.matches(None)

    def test_catalog_applies_rule(self):
        """Trazodone's CYP2D6 UM rule should shrink its profile-effect multiplier."""
        from optiqal.catalog import CATALOG
        from optiqal.profile import Profile

        base_profile = Profile(
            age=39, sex="male", bmi_category="normal", smoking_status="never",
            has_diabetes=False, has_hypertension=False, activity_level="light",
        )
        trazodone = CATALOG["trazodone_50mg"]

        base_mult = trazodone.profile_effect_multiplier(base_profile)

        um_profile = Profile(
            age=39, sex="male", bmi_category="normal", smoking_status="never",
            has_diabetes=False, has_hypertension=False, activity_level="light",
            genetic_profile=GeneticProfile(
                phenotypes={"CYP2D6": "ultrarapid_metabolizer"},
            ),
        )
        um_mult = trazodone.profile_effect_multiplier(um_profile)
        # With UM rule (0.3x), multiplier should be strictly smaller.
        assert um_mult == pytest.approx(base_mult * 0.3, rel=1e-6)

    def test_catalog_no_rule_no_change(self):
        """Items without genetic rules shouldn't change with genetic_profile."""
        from optiqal.catalog import CATALOG
        from optiqal.profile import Profile

        # finasteride has no genetic rules
        fin = CATALOG["finasteride_1.25mg"]
        p_no = Profile(
            age=39, sex="male", bmi_category="normal", smoking_status="never",
            has_diabetes=False, has_hypertension=False, activity_level="light",
        )
        p_with_pgx = Profile(
            age=39, sex="male", bmi_category="normal", smoking_status="never",
            has_diabetes=False, has_hypertension=False, activity_level="light",
            genetic_profile=GeneticProfile(
                phenotypes={"CYP2D6": "poor_metabolizer"},
            ),
        )
        assert fin.profile_effect_multiplier(p_no) == fin.profile_effect_multiplier(p_with_pgx)


class TestReport:
    def test_renders_markdown(self, tmp_path):
        from optiqal.genetics.reports import render_markdown_report
        p = _write_23andme(tmp_path, {
            "rs3892097": ("22", 42128945, "AA"),  # CYP2D6 *4/*4 → PM
            "rs1065852": ("22", 42130692, "CC"),
            "rs28371706": ("22", 42127941, "CC"),
            "rs28371725": ("22", 42129770, "GG"),
            "rs4244285": ("10", 96541616, "GG"),
            "rs4986893": ("10", 96540410, "GG"),
            "rs12248560": ("10", 96522463, "CC"),
            "rs1800562": ("6", 26093141, "GG"),
            "rs1799945": ("6", 26091179, "CC"),
            "rs429358": ("19", 45411941, "TC"),
            "rs7412": ("19", 45412079, "CC"),
        })
        gp = build_genetic_profile(p, run_ashkenazi_brca=False)
        report = render_markdown_report(gp)
        assert "Pharmacogenomics" in report
        assert "CYP2D6" in report
        assert "Poor metabolizer" in report
        assert "APOE" in report
        assert "e3/e4" in report
        # Privacy header
        assert "publishable: false" in report
